import type { Metadata } from 'next';
import 'remixicon/fonts/remixicon.css';
import ThemeProvider from '~/components/providers/theme-provider';
import fonts from '~/configs/fonts';
import cn from '~/utils/cn';
import './globals.css';

export const metadata: Metadata = {
  title: 'Messalo',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="vi">
      <body className={cn(fonts.sans.className)}>
        <ThemeProvider attribute="class">{children}</ThemeProvider>
      </body>
    </html>
  );
}
